Conference Page
Ayokunnumi1/Conference-Page pull request #1
Opened 2023-07-07 17:27 UTC by Ayokunnumi1

These are the functionalities implemented in this project;
* Home Page and About Page
* Responsive design for mobile and desktop
* Interactive links in mobile menu and desktop navbar.
* Dynamic Creation of the Featured Speakers Section,
* Zero Linter Errors

2023-07-07 19:39 UTC, Efiamotu-1 requested changes
Hi @Ayokunnumi1 , 

![](https://user-images.githubusercontent.com/89055502/221963929-dc172827-5c2c-411b-bf4d-923659f626e1.gif) 

Good job so far! 👏. Your Code is Awesome! 💪

There are some **few** issues 🐛 that you still need to work 🔧 on though to go to the next project ⏭️ but you are almost there! 🏃
## Don't Worry 🙏

It's ok to have bugs in your code 🐛. Please, see this code review as a **chance** for you to **learn** practical coding skills and learn **new tips** that can improve your code quality 💯 and help you **get a better ** 💼.

_I am going to guide you on how to fix them down below. 🤓_

## Highlights :dart: 
- ✔️ No linter Errors
- ✔️ Descriptive README
- ✔️ Descriptive PR title and description
- The code is top-notch! 💯 and has a huge potential.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-07 19:39 UTC, Efiamotu-1 commented on README.md
> +I give thanks to the Microverse team for creating this project.
- [ ] Your "Acknowledgements" section should gives appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/).

2023-07-07 19:39 UTC, Efiamotu-1 commented on README.md
> +- [Live Demo Link]()
- [ ] Your live demo currently doesn't show the live working version of your project hosted on github pages. Please i kindly suggest your host your project using github pages. The live version is important as it demo's your project for anyone checking it out :+1:

2023-07-07 19:39 UTC, Efiamotu-1 commented on index.html
> +        <div class="mobile-navbar">
- [ ] As shown in the images below on mobile view you are to only show the hamburger menu icon, but from your design your logo is also displaying. please kindly follow the provided project design 👍 
- project design
![cc](https://github.com/Ayokunnumi1/Conference-Page/assets/89055502/2023172a-f45f-4b8e-a6b3-dc2aca201b42)
- your design
![cc ham](https://github.com/Ayokunnumi1/Conference-Page/assets/89055502/c5dd1bf6-26b0-4cdb-95c8-c9512ae89ee5)

2023-07-07 19:39 UTC, Efiamotu-1 commented on index.html
> +                </p>
- [ ] As shown in the project design below the text are much larger than what you currently have on your design, i will kindly suggest that your increase the text size to match closely the provided project design 👍 
- project design
![ht](https://github.com/Ayokunnumi1/Conference-Page/assets/89055502/5ad3fe33-40b1-4193-8c05-e9b198d5019e)
- your design
![hts](https://github.com/Ayokunnumi1/Conference-Page/assets/89055502/dc279d7e-6e13-46c4-a6b9-6e91940cb55f)

2023-07-07 19:39 UTC, Efiamotu-1 commented on index.html
> +                    <h3>CC Exhibition</h3>
- [ ] Please kindly note that for each program the white border only becomes visible when a user hovers around it as shown in the provided design template below. However what you have is the white borders displaying and no spaces between each program. Please kindly make the necessary adjustments.
- [ ] Each program should also have the appropriate background image as shown in the provided project design
- project design
![sp](https://github.com/Ayokunnumi1/Conference-Page/assets/89055502/6c096c62-514b-4573-8965-9305e404e816)
- your design
![yd](https://github.com/Ayokunnumi1/Conference-Page/assets/89055502/123c49cc-67fd-4bec-95be-2103116f3609)

2023-07-07 19:39 UTC, Efiamotu-1 commented on about.html
> +                    <p class="header-theme abt-header-theme">"You Never Fail Until You Stop Trying"</p>
- [ ] Please kindly center the text on the about page for mobile screens, you can see the red arrows showing a guide for  both your design and the template design   
- project design
![ct](https://github.com/Ayokunnumi1/Conference-Page/assets/89055502/d8b31aea-ac27-4b74-9595-ce11b521cb42)
- your design
![cts](https://github.com/Ayokunnumi1/Conference-Page/assets/89055502/bdbea99d-19d0-4d34-80bb-990204270813)

2023-07-07 19:39 UTC, Efiamotu-1 commented on about.html
> +    <section id="Partner" class="partner-container abt-partner-container">
- [ ] Your partners section on mobile devices doesn't have the appropriate spacing as seen in the provided image below, please kindly adjust your design.
- project design
![pt](https://github.com/Ayokunnumi1/Conference-Page/assets/89055502/e1abc84e-5263-4284-9737-828c8f27a4cb)
- your design
![pts](https://github.com/Ayokunnumi1/Conference-Page/assets/89055502/88ed19da-da3f-4f8d-9f8f-140b714c578b)

2023-07-07 19:39 UTC, Efiamotu-1 commented on about.html
> +    <footer class="footer">
- [ ] Your about footer for desktop device doesn't have the correct background color as can be seen in the project design provided to you 
- project design
![ab-ft](https://github.com/Ayokunnumi1/Conference-Page/assets/89055502/8af1ff22-c004-4442-ae5a-e60eb3bee583)

2023-07-08 01:07 UTC, anagudelogu requested changes
# STATUS: CHANGES REQUIRED ♻️ 🚧 

Hi @Ayokunnumi1 👋🏼 
I'm Andres.

You've done a great job implementing some of the requested changes for this milestone 🚀, but there are still some which haven't been addressed yet. You're getting closer, keep up the good work! 🤖 🎆 

<img src="https://media2.giphy.com/media/3ohhwi25ISXC7Z4tMs/giphy-downsized-medium.gif"/>

 ## Highlights
✅ Great use of GitHub flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Great UI design. 💻 
✅ Descriptive PR title, summary and commit messages. 💬 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-08 01:07 UTC, anagudelogu commented on index.html
> +                        <img src="images/lecture-img.png" alt="">
- [ ] You did a good job working on the previous reviewer's suggestions! 💯 However, there's still some room to improve the quality of your changes:

| Template |
|---|
| ![image](https://github.com/Ayokunnumi1/Conference-Page/assets/77069011/a4b3c44e-43bf-46bf-932b-f132b03becb3) |

| Your design |
|---|
| ![image](https://github.com/Ayokunnumi1/Conference-Page/assets/77069011/df5cba62-a1ee-4b47-8c65-b5e61b8bad89) |

If you see, the spacing is not the same as shown in the template, this visual bug got introduced in the latest changes you made. Please fix it! 🤓 🔧

2023-07-08 01:07 UTC, anagudelogu commented on about.html
> +                </div>
- [ ] As requested by the previous reviewer, please consider centering the content of the header section on your `About` page. Remember that is important to stick as much as possible to the given design:

|Template|Your design|
|---|---|
| ![image](https://github.com/Ayokunnumi1/Conference-Page/assets/77069011/45ed6c1d-5a45-4359-b562-64c6843e87fe) | ![image](https://github.com/Ayokunnumi1/Conference-Page/assets/77069011/ed7e9044-606f-44dc-bf2a-08c0cc4e16ee) |

Please consider fixing the alignment! 🤓 🔧

2023-07-08 12:50 UTC, iambenkis approved these changes
# Approved 👏  
### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

✅ Great use of GitHub flow. 💯
✅ Your project is documented professionally. 📜
✅ Great UI design. 💻
✅ Descriptive PR title, summary and commit messages. 💬

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
![image](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @iambenkis in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-08 13:56 UTC, merged